### ISSUE TITLE
Bluebuild-built entities don't have a Bottleneck indicator

### ISSUE THREAD

**Issue by bigyihsuan** [troelsbjerre/Bottleneck#11]
This is an issue with [Bluebuild](https://mods.factorio.com/mods/Mylon/Bluebuild).

The furnaces with indicators are the ones built by construction bots. The ones without were built with Bluebuild.

http://i.imgur.com/ooYkffe.png

A possible cause is [looking for a player or bot-built entity](https://github.com/troelsbjerre/Bottleneck/blob/master/control.lua#L222-L244). Bluebuild might not call this function when building its entities.

**Comment by troelsbjerre** [comment]
It seems like Bluebuild fails to trigger the appropriate events, when creating new entities. Because of this, Bluebuild also has a problem with other mods that depend on this, like the mod Autofill. Furthermore, I do not see an efficient way to fix the problem inside Bottleneck, since it would require constant scanning for entities that have snuck into the map under the radar.

**Comment by troelsbjerre** [comment]
This issue was fixed by Bluebuild 0.6.4.
