### ISSUE TITLE
Some issues with compatability with NPE

### ISSUE THREAD

**Issue by wheybags** [troelsbjerre/Bottleneck#47]
Hi, just wanted to let you know that some users are reporting errors when running the new "Introduction" scenario while they have your mod installed.
Here's the bug reports on our forums, moved to "not a bug" because I believe the issue is on your side.

https://forums.factorio.com/viewtopic.php?f=226&t=65305
https://forums.factorio.com/viewtopic.php?f=226&t=65307

**Comment by troelsbjerre** [comment]
Yes, it's an issue on our side. I'm guessing the floating lights are due to some scripted entities in the scenario that we just treat as normal entities. I have no clue what causes the crash bug. However, the mod is due for an overhaul with the nice 0.17 api, so the bugs might go away in the overhaul. It will be a few days before I can find the time for this :(

**Comment by Nexela** [comment]
Reminder to self to publish the pr with some examples.  !

**Comment by wheybags** [comment]
So, I think what's happening is that we use the new [clone_area method](https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.clone_area), and it's cloning your icon entities. You should be able to use [on_area_cloned](https://lua-api.factorio.com/latest/events.html#on_area_cloned) somehow to prevent this.

**Comment by troelsbjerre** [comment]
I've added a check on_entity_cloned that checks whether it's a bottleneck-signal, and if so, destroys it. I am not sure it's the right way, but it appears to have fixed the NPE issue described above. Fixed in v0.10.2
